trigger:
  - main

pool: "vagrant"
#  vmImage: 'self hosted' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  imageName: 'pipelines-javascript-docker'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: app/Dockerfile
  - task: aquasec.aquasec.showCommits.aquasecScanner@4
    displayName: 'Image Scanning'
    inputs:
      image: pipelines-javascript-docker:$(Build.BuildId)
      scanner: 'registry.aquasec.com/scanner:6.5'
      connection: 'Aqua-MDG'
      registerCompliant: true